version: "3.8"

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}

  api:
    depends_on:
      - db
    build: .
    command: npm run start:dev
    restart: unless-stopped
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/app
