version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: ${NODE_ENV}
    # Mount our host Directory to the docker container
    # Mount (.) current directory to the docker container /src/app
    # reflect file changes from host to container
    volumes:
      - .:/usr/app
      - .:/usr/app/node_modules
    # Run in dev Mode: npm run start:dev
    # Run in prod Mode: npm run start:prod
    command: ${COMMAND}
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DB_URL}
      PORT: 3333
    ports:
      - 3333:3333

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432

