version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    # Mount our host Directory to the docker container
    # Mount (.) current directory to the docker container /src/app
    # reflect file changes from host to container
    volumes:
      - .:/usr/app
      - .:/usr/app/node_modules
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DB_URL}
      PORT: 8080
    ports:
      - 8080:8080

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432

    ### Postgres Adminer ###
  postgres_admin:
    image: dpage/pgadmin4:4.28
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.de
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
